export type TeacherProfile = {
  slug: string;
  name: string;
  initials: string;
  subjects: string[];
  publicFocus: string[];
  evidenceStatus: "official-current-section" | "official-archive-profile";
  evidenceNote: string;
  sourceUrl: string;
  participation: "project-lead-by-brief" | "not-confirmed";
  skillSlug: string;
};

const CURRENT_OD = "https://www.stpku.ru/index.php/uchebnyj-protsess/otdelnye-distsipliny/od-russkij-yazyk-i-literatura";
const ARCHIVE_STAFF = "https://arhive.stpku.ru/index.php?Itemid=257&id=888&option=com_content&view=article";

export const russianTeachers: TeacherProfile[] = [
  { slug: "elena-mikhaylichenko", name: "Елена Николаевна Михайличенко", initials: "ЕМ", subjects: ["Русский язык", "Литература", "ОГЭ", "ЕГЭ"], publicFocus: ["подготовка к ОГЭ и ЕГЭ", "литературное наследие М. А. Шолохова", "креативное мышление"], evidenceStatus: "official-archive-profile", evidenceNote: "Профиль и публикации есть в официальном архиве СПКУ; актуальный статус в штате нужно подтвердить. Роль основного эксперта задана владельцем проекта.", sourceUrl: ARCHIVE_STAFF, participation: "project-lead-by-brief", skillSlug: "elena-mikhaylichenko-russian-tutor" },
  { slug: "marina-bovina", name: "Марина Александровна Бовина", initials: "МБ", subjects: ["Русский язык", "Литература"], publicFocus: ["углублённая и олимпиадная подготовка", "сложные синтаксические конструкции", "лингвокультурные проекты"], evidenceStatus: "official-current-section", evidenceNote: "Профиль есть в официальном архиве, деятельность упоминается на действующем сайте СПКУ; участие в платформе не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "marina-bovina-russian-tutor" },
  { slug: "svetlana-vorobieva", name: "Светлана Викторовна Воробьева", initials: "СВ", subjects: ["Русский язык", "Литература"], publicFocus: ["читательская грамотность", "экзаменационные задания с развёрнутым ответом", "олимпиадная практика"], evidenceStatus: "official-current-section", evidenceNote: "Публичные материалы СПКУ подтверждают филологические викторины и экзаменационную подготовку; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "svetlana-vorobieva-russian-tutor" },
  { slug: "elina-german", name: "Элина Эдуардовна Герман", initials: "ЭГ", subjects: ["Русский язык", "Литература"], publicFocus: ["морфология и служебные части речи", "литературный текст и живопись", "ОГЭ и ЕГЭ по литературе"], evidenceStatus: "official-current-section", evidenceNote: "Открытый урок на действующем сайте и архивный профиль СПКУ; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "elina-german-russian-tutor" },
  { slug: "roman-gorbunov", name: "Роман Сергеевич Горбунов", initials: "РГ", subjects: ["Русский язык", "Литература"], publicFocus: ["литературный клуб и лекторий", "Набоковские чтения", "исследовательское обсуждение текста"], evidenceStatus: "official-current-section", evidenceNote: "Действующий сайт СПКУ называет соавтором лектория 2026 года; участие в платформе не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "roman-gorbunov-russian-tutor" },
  { slug: "tamara-dedova", name: "Тамара Валерьевна Дедова", initials: "ТД", subjects: ["Русский язык", "Литература"], publicFocus: ["практико-ориентированный урок", "межпредметные квесты", "современная литература и семейное чтение"], evidenceStatus: "official-current-section", evidenceNote: "Официальные новости СПКУ 2024–2026 подтверждают открытые уроки и семинары; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "tamara-dedova-russian-tutor" },
  { slug: "tatyana-ivanova", name: "Татьяна Александровна Иванова", initials: "ТИ", subjects: ["Русский язык", "Литература"], publicFocus: ["синтаксис и пунктуация", "обобщающий практикум", "учебные экскурсии"], evidenceStatus: "official-current-section", evidenceNote: "Упомянута как преподаватель ОД в публикациях СПКУ 2026 года; отдельный архивный профиль не найден, участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "tatyana-ivanova-russian-tutor" },
  { slug: "darya-kuznetsova", name: "Дарья Владиславовна Кузнецова", initials: "ДК", subjects: ["Русский язык", "Литература"], publicFocus: ["проектные уроки литературы", "нравственный выбор в тексте", "заимствованная лексика"], evidenceStatus: "official-current-section", evidenceNote: "На официальном сайте доступны технологические карты и открытые уроки; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "darya-kuznetsova-russian-tutor" },
  { slug: "olga-menshakova", name: "Ольга Михайловна Меньшакова", initials: "ОМ", subjects: ["Русский язык", "Литература"], publicFocus: ["осмысленное чтение", "итоговая аттестация", "олимпиадная подготовка"], evidenceStatus: "official-current-section", evidenceNote: "Публикации и открытые занятия находятся на действующем сайте, квалификации — в официальном архиве; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "olga-menshakova-russian-tutor" },
  { slug: "lyudmila-molokanova", name: "Людмила Александровна Молоканова", initials: "ЛМ", subjects: ["Русский язык", "Литература"], publicFocus: ["филологическая исследовательская работа", "игровые образовательные форматы", "олимпиадная литература"], evidenceStatus: "official-archive-profile", evidenceNote: "Подтверждён только архивный профиль СПКУ; актуальную работу и участие необходимо подтвердить.", sourceUrl: ARCHIVE_STAFF, participation: "not-confirmed", skillSlug: "lyudmila-molokanova-russian-tutor" },
  { slug: "ekaterina-moskvitina", name: "Екатерина Александровна Москвитина", initials: "ЕМ", subjects: ["Русский язык", "Литература"], publicFocus: ["литературный клуб", "глубокое чтение", "культурный контекст произведения"], evidenceStatus: "official-current-section", evidenceNote: "Действующий сайт СПКУ называет соавтором лектория 2026 года; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "ekaterina-moskvitina-russian-tutor" },
  { slug: "anna-podrezova", name: "Анна Васильевна Подрезова", initials: "АП", subjects: ["Русский язык", "Литература"], publicFocus: ["литература через театр", "сочинения и проекты", "подготовка к ОГЭ и ЕГЭ"], evidenceStatus: "official-current-section", evidenceNote: "Деятельность и архивный профиль опубликованы СПКУ; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "anna-podrezova-russian-tutor" },
  { slug: "marina-ustinova", name: "Марина Ивановна Устинова", initials: "МУ", subjects: ["Русский язык", "Литература"], publicFocus: ["интеллект-карты", "активные методы обучения", "ОГЭ и ЕГЭ по литературе"], evidenceStatus: "official-archive-profile", evidenceNote: "Подтверждён только архивный профиль СПКУ; актуальную работу и участие необходимо подтвердить.", sourceUrl: ARCHIVE_STAFF, participation: "not-confirmed", skillSlug: "marina-ustinova-russian-tutor" },
  { slug: "viktoria-tsynkevich", name: "Виктория Владимировна Цынкевич", initials: "ВЦ", subjects: ["Русский язык", "Литература"], publicFocus: ["сочинение-рассуждение", "лингвистические викторины", "психологическая подготовка к экзамену"], evidenceStatus: "official-current-section", evidenceNote: "Официальные материалы СПКУ показывают экзаменационный и игровой профиль; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "viktoria-tsynkevich-russian-tutor" },
  { slug: "elena-shirokaya", name: "Елена Николаевна Широкая", initials: "ЕШ", subjects: ["Русский язык", "Литература"], publicFocus: ["речевое мастерство", "читательская грамотность", "устная речь и ОГЭ/ЕГЭ"], evidenceStatus: "official-current-section", evidenceNote: "Действующий сайт СПКУ содержит открытые уроки 2025–2026 годов; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "elena-shirokaya-russian-tutor" },
  { slug: "larisa-shutova", name: "Лариса Дмитриевна Шутова", initials: "ЛШ", subjects: ["Русский язык", "Литература"], publicFocus: ["прогнозирование содержания текста", "читательская грамотность", "экзаменационная литература"], evidenceStatus: "official-current-section", evidenceNote: "Деятельность упоминается на действующем сайте СПКУ, профиль — в официальном архиве; участие не подтверждено.", sourceUrl: CURRENT_OD, participation: "not-confirmed", skillSlug: "larisa-shutova-russian-tutor" },
];
